
require(gtools)
require(Hmisc)
require(gplots)
require(LSD)
require(corrplot)
library(igraph)
require(plotrix)
library(scales)
library(grid)
library(reshape2)
require(drc)
library(ggsci)
library(Hmisc)
library(RColorBrewer)
require(drm)
library(growthcurver)
library(pheatmap)
library(plotly)
library(data.table)
library(gifski)
library(gridExtra)
library(gganimate)
library(dplyr)
library(ggpubr)
library(tibble)
library(data.table)
library(magick)
library(tidyverse)
library(RCircos)
require(gtools)
require(graphics)
require(stats)
require(zoo)
require(corrplot)
library(igraph)
require(plotrix)
library(matrixStats)
require(drc)
library(ggrepel)
library(ggplot2)
library(ggridges)
library(gsubfn) 
library(lubridate)

ID <- c()
activity_time <- c()
recognized_activity <- c()
basic_activity <- c()
activity_details <- c()

test <- data.frame(read_csv("/Users/bassler/Desktop/Combined_data.csv"))
for (e in 1:nrow(test)){
  text <- strsplit(test[e,], split = "_") [[1]]
  ID <- c(ID, text[1])
  activity_time <- c(activity_time, as.character(ymd_hms(gsub("[T]", " ",text [2]), tz = "CET")))
  recognized_activity <- c(recognized_activity, text[3])
  basic_activity <- c(basic_activity, text[4])
  activity_details <- c(activity_details, text[5])
}

basic_activity <- gsub("[^A-Za-z0-9: ,]", "", basic_activity)
full_data <- data.frame(ID, activity_time, recognized_activity, activity_details, basic_activity)
write.table(full_data, "/Users/bassler/Desktop/Combined_data_final.csv")


